#!/bin/sh

echo "${TEST_NAME} -- test whether absolute symlinks are followed"

set -- ${PYTHON_IMPLS}

if [ ${#} -lt 1 ]; then
	echo 'No Python implementation supported (?!)' >&2
	do_exit 77
fi

export EPYTHON=${1}

echo "EPYTHON: ${EPYTHON}" >&2

write_impl "${EPYTHON}" "#!/usr/bin/env true"
do_sym "${PWD}/${TEST_DIR}/${TEST_TMP}" "${TEST_TMP}.symlink"

do_test "${TEST_TMP}.symlink"
