#!/bin/sh

echo "${TEST_NAME} -- test whether python-exec2c can be symlinked as wrapper"

set -- ${PYTHON_IMPLS}

if [ ${#} -lt 1 ]; then
	echo 'No Python implementation supported (?!)' >&2
	do_exit 77
fi

export EPYTHON=${1}

write_impl "${EPYTHON}" "#!/bin/sh\nexit 0"

echo "EPYTHON: ${EPYTHON}" >&2

# replace with C wrapper
rm "${TEST_DIR}/${TEST_TMP}"
ln -s ../bin/python-exec2c "${TEST_DIR}/${TEST_TMP}"

do_test "${TEST_TMP}"
