#!/bin/sh

echo "${TEST_NAME} -- test whether deep symlinks are followed"

set -- ${PYTHON_IMPLS}

if [ ${#} -lt 1 ]; then
	echo 'No Python implementation supported (?!)' >&2
	do_exit 77
fi

export EPYTHON=${1}

echo "EPYTHON: ${EPYTHON}" >&2

write_impl "${EPYTHON}" "#!/usr/bin/env true"
ln -s "${TEST_TMP##*/}" "${TEST_TMP}-symI"
ln -s "${TEST_TMP##*/}-symI" "${TEST_TMP}-symII"
ln -s "${TEST_TMP##*/}-symII" "${TEST_TMP}-symIII"

do_test "${TEST_TMP}-symIII"
