#!/bin/sh

echo "${TEST_NAME} -- test whether disabling impl works correctly"

set -- ${PYTHON_IMPLS}

while true; do
	if [ ${#} -lt 2 ]; then
		# we can't test this without disabled impl
		echo 'No disabled implementations to perform test.' >&2
		do_exit 77
	fi

	if is_disabled "${1}"; then
		break
	fi
	shift
done

DISABLED="${1}"
unset EPYTHON

echo "DISABLED: ${DISABLED}" >&2

write_impl "${DISABLED}" "#!/usr/bin/env true"

do_test "${TEST_TMP}"
