#!/bin/sh

echo "${TEST_NAME} -- test whether EPYTHON overrides disabled impl"

set -- ${PYTHON_IMPLS}

while true; do
	if [ ${#} -lt 2 ]; then
		# we can't test a preference without disabled impl
		echo 'No disabled implementations to perform test.' >&2
		do_exit 77
	fi

	if is_disabled "${1}"; then
		break
	fi
	shift
done

export EPYTHON="${1}"

echo "EPYTHON: ${EPYTHON}" >&2

write_impl "${EPYTHON}" "#!/usr/bin/env true"

do_test "${TEST_TMP}"
