#!/bin/sh
# Test whether EPYTHON is respected.

echo "${TEST_NAME} -- test whether EPYTHON is respected"

set -- ${PYTHON_IMPLS}

if [ ${#} -le 2 ]; then
	# we can't test a preference without at least two impls ;)
	echo 'Not enough implementations to perform test.' >&2
	do_exit 77
fi

export EPYTHON=${1}
BETTER=${2}

echo "EPYTHON: ${EPYTHON}" >&2
echo "other impl: ${BETTER}" >&2

write_impl "${EPYTHON}" "#!/usr/bin/env true"
write_impl "${BETTER}"  "#!/usr/bin/env false"

do_test "${TEST_TMP}"
