#!/bin/sh
# Test whether EPYTHON is respected.

echo "${TEST_NAME} -- test whether EPYTHON is respected"

set -- ${PYTHON_IMPLS}

SEL_PY2=$(get_eselected --python2)
SEL_PY3=$(get_eselected --python3)

while true; do
	if [ ${#} -lt 2 ]; then
		# we can't test a preference without at least two impls ;)
		echo 'Not enough implementations to perform test.' >&2
		do_exit 77
	fi

	# EPYTHON can't be one of eselected pythons, otherwise the result
	# would be inconclusive.
	if [ "${1}" = "${SEL_PY2}" -o "${1}" = "${SEL_PY3}" ]; then
		shift
	else
		break
	fi
done

export EPYTHON=${1}
BETTER=${2}

echo "EPYTHON: ${EPYTHON}" >&2
echo "other impl: ${BETTER}" >&2

write_impl "${EPYTHON}" "#!/usr/bin/env true"
write_impl "${BETTER}"  "#!/usr/bin/env false"

do_test "${TEST_TMP}"
