#!/bin/sh

echo "${TEST_NAME} -- test whether long paths (>BUFSIZ) work"

bufsiz=$(src/print-bufsiz)

if [ -z "${bufsiz}" ]; then
	echo 'BUFSIZ unknown' >&2
	do_exit 77
fi

# bufsiz + temporary prefix > bufsiz :)
longfn=$(printf "%0${bufsiz}d" 1)

set -- ${PYTHON_IMPLS}

if [ ${#} -lt 1 ]; then
	echo 'No Python implementation supported (?!)' >&2
	do_exit 77
fi

export EPYTHON=${1}

echo "EPYTHON: ${EPYTHON}" >&2

if ! write_impl "${longfn}-${EPYTHON}" "#!/usr/bin/env true"; then
	do_exit 77
fi
mv "${TEST_TMP}" "${TEST_TMP}-${longfn}"

do_test "${TEST_TMP}-${longfn}"
