#!/bin/sh

echo "${TEST_NAME} -- test whether long (>BUFSIZ) symlinks work"

bufsiz=$(test/bin/print-bufsiz)

if [ -z "${bufsiz}" ]; then
	echo 'BUFSIZ unknown' >&2
	do_exit 77
fi

# bufsiz + temporary prefix > bufsiz :)
longfn=$(printf "%0${bufsiz}d" 2)

set -- ${PYTHON_IMPLS}

if [ ${#} -lt 1 ]; then
	echo 'No Python implementation supported (?!)' >&2
	do_exit 77
fi

export EPYTHON=${1}

echo "EPYTHON: ${EPYTHON}" >&2

if ! write_impl "${EPYTHON}" "#!/usr/bin/env true" "-${longfn}"; then
	do_exit 77
fi
mv "${TEST_DIR}/${TEST_TMP}" "${TEST_DIR}/${TEST_TMP}-${longfn}"
do_sym "${TEST_TMP}-${longfn}" "${TEST_TMP}"

do_test "${TEST_TMP}"
