#!/bin/sh

echo "${TEST_NAME} -- test whether Python wrapper works when copied (instead of symlinked)"

set -- ${PYTHON_IMPLS}
GOOD=0
BAD=0

# replace with a copy
rm "${TEST_DIR}/${TEST_TMP}"
cp "${TEST_DIR}/python-exec2" "${TEST_DIR}/${TEST_TMP}"

while [ ${#} -gt 0 ]; do
	export EPYTHON="${1}"
	shift

	# We have to have the proper Python version installed.
	if ! "${EPYTHON}" --version >&2; then
		continue
	fi

	echo "Testing Python: ${EPYTHON}" >&2
	write_impl "${EPYTHON}" "import sys; sys.exit(0)"

	if do_test_noexit "${EPYTHON}" "${TEST_TMP}"; then
		: $(( GOOD += 1 ))
	else
		: $(( BAD += 1 ))
	fi
done

if [ ${BAD} -eq 0 ]; then
	if [ ${GOOD} -eq 0 ]; then
		echo 'No working Python interpreter found (?!)' >&2
		do_exit 77
	else
		do_exit 0
	fi
else
	do_exit 1
fi
