#!/bin/sh

echo "${TEST_NAME} -- test whether Python wrapper follows (relative) symlinks"

set -- ${PYTHON_IMPLS}

while true; do
	if [ ${#} -lt 1 ]; then
		echo 'No working Python intepreter found (?!)' >&2
		do_exit 77
	fi

	# We have to have the proper Python version installed.
	if ! "${1}" --version >&2; then
		shift
	else
		break
	fi
done

MY_PYTHON=${1}

echo "Python used: ${MY_PYTHON}" >&2

write_impl "${MY_PYTHON}" "import sys; sys.exit(0)"
ln -s "${PWD}/${TEST_TMP}" "${TEST_TMP}.symlink"

do_test "${MY_PYTHON}" "${TEST_TMP}.symlink"
