#!/bin/sh

echo "${TEST_NAME} -- test whether all implementations are tested before following symlink"

set -- ${PYTHON_IMPLS}

if [ ${#} -lt 2 ]; then
	echo 'This test requires at least two Python implementations supported.' >&2
	do_exit 77
fi

while true; do
	if [ ${#} -lt 3 ]; then
		# we need at least two impls
		echo 'Not enough implementations to perform test.' >&2
		do_exit 77
	fi

	# the 'preferred' impl must not be disabled
	if ! is_disabled "${1}"; then
		break
	fi
	shift
done

FIRST=${1}
export EPYTHON=${2}

echo "first: ${FIRST}" >&2
echo "EPYTHON: ${EPYTHON}" >&2

write_impl "${FIRST}" "#!/usr/bin/env true" "-sym"
write_impl "${EPYTHON}" "#!/usr/bin/env false"
do_sym "${TEST_TMP}" "${TEST_TMP}-sym"

do_test "${TEST_TMP}-sym"
