#!/bin/sh

echo "${TEST_NAME} -- test whether Python wrapper works when copied (instead of symlinked)"

set -- ${PYTHON_IMPLS}

if [ ${#} -lt 1 ]; then
	echo 'No Python implementation supported (?!)' >&2
	do_exit 77
fi

export EPYTHON=${1}

write_impl "${EPYTHON}" "#!/bin/sh\nexit 0"

# replace with a copy
rm "${TEST_DIR}/${TEST_TMP}"
cp test/bin/python-exec2c "${TEST_DIR}/${TEST_TMP}"

do_test "${TEST_TMP}"
